# example netlify.toml
[build]
  command = "hugo build"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "v0.140.2"

[[redirects]]
from = "/aims-objectives"
to = "/about"

[[redirects]]
from = "/blog-posts"
to = "/blog"

[[redirects]]
from = "/resources-2"
to = "/resources"